log.scrpt("game.script")

go.property("_ply_slt_idx", 0)
go.property("_map_id", hash(""))
go.property("_dia_id", hash(""))
go.property("_dstrct", vmath.vector3(0, 0, 0))

go.property("_sky_id" , hash(""))

function init(_s)
	Game.init(_s)
end

--[[ upd
function update(_s, dt)
	_s:upd(dt)
end --]]

function on_message(_s, msg_id, prm, sndr_url)
	_s:on_msg(msg_id, prm, sndr_url)
end

function final(_s)
	_s:final()
end

