log.scrpt("gold.script")
---[[
go.property("_clsHa",  hash(""))
go.property("_nameHa", hash(""))
go.property("_animHa", hash(""))

go.property("_game_id", hash(""))
go.property("_map_id",  hash(""))

go.property("_parent_id", hash(""))
go.property("_z", 0.2)
--]]
go.property("_price", 0)

function init(_s)
	Gold.init(_s)
end

function update(_s, dt)	
	_s:upd(dt)
end

function on_message(_s, msg_id, prm, sndr)
	_s:on_msg(msg_id, prm, sndr)
end

function final(_s)
	_s:final()
end

